export const mediaIdentityMessages:Record<string,readonly[string,string,string,string]>={
  "원본 파일 검증 정보가 유효하지 않습니다.":["The source file verification data is invalid.","元ファイルの検証情報が無効です。","原始文件验证信息无效。","Los datos de verificación del original no son válidos."],
  "연결한 파일과 서버의 원본 검증 정보가 다릅니다.":["The connected file does not match the server's source verification data.","接続したファイルとサーバーの元ファイル検証情報が一致しません。","连接的文件与服务器的原始文件验证信息不一致。","El archivo conectado no coincide con la verificación del servidor."],
  "프로젝트에 등록된 원본과 다른 파일입니다. 원본을 다시 연결하거나 새 프로젝트로 시작하세요.":["This file differs from the project's registered source. Reconnect the original or start a new project.","プロジェクトに登録された元ファイルと異なります。元ファイルを再接続するか、新規プロジェクトを開始してください。","此文件与项目记录的原始文件不同。请重新连接原文件或新建项目。","Este archivo difiere del original registrado. Reconecta el original o inicia un proyecto nuevo."],
  "이 프로젝트에는 원본 검증 정보가 없습니다. 원본을 다시 연결하고 확인하세요.":["This project has no source verification data. Reconnect and confirm the source file.","このプロジェクトには元ファイルの検証情報がありません。元ファイルを再接続して確認してください。","此项目没有原始文件验证信息。请重新连接并确认原文件。","Este proyecto no tiene datos de verificación. Reconecta y confirma el original."],
  "원본 파일을 확인하고 연결했습니다.":["Source file verified and connected.","元ファイルを確認して接続しました。","已验证并连接原始文件。","Original verificado y conectado."],
  "선택한 파일은 프로젝트에 등록된 원본과 내용이 다릅니다. 기존 자막·메모·컷을 재사용하지 않고 새 프로젝트로 시작합니다. 현재 작업이 필요하면 먼저 저장하세요.":["The selected file has different content from the registered source. A new project will start without reusing the existing subtitles, notes or cuts. Save the current work first if needed.","選択したファイルは登録済みの元ファイルと内容が異なります。既存の字幕・メモ・カットを再利用せず新規プロジェクトを開始します。必要な作業は先に保存してください。","所选文件的内容与登记的原始文件不同。将新建项目，不复用现有字幕、备注或剪辑。如需保留当前工作，请先保存。","El contenido difiere del original registrado. Se iniciará un proyecto nuevo sin reutilizar subtítulos, notas ni cortes. Guarda primero el trabajo actual si lo necesitas."],
  "이 파일로 새 프로젝트 시작":["Start a new project with this file","このファイルで新規プロジェクトを開始","用此文件新建项目","Crear proyecto con este archivo"],
  "이 프로젝트에는 원본 해시가 없어 같은 원본인지 자동 확인할 수 없습니다. 선택한 파일이 원본인지 직접 확인하세요. 계속하면 기존 자막·메모·컷 시간을 유지하고 이 파일을 앞으로의 원본 기준으로 등록합니다.":["This project has no source hash, so the original cannot be verified automatically. Confirm that the selected file is the original. Continuing keeps existing subtitle, note and cut times and registers this file as the source for future checks.","このプロジェクトには元ファイルのハッシュがないため自動検証できません。選択したファイルが元ファイルであることを確認してください。続行すると字幕・メモ・カットの時刻を維持し、このファイルを今後の検証基準に登録します。","此项目没有原始文件哈希，无法自动确认是否为同一原文件。请自行确认所选文件。继续后会保留字幕、备注和剪辑时间，并将此文件登记为今后验证的基准。","Este proyecto no tiene hash del original y no puede verificarse automáticamente. Confirma que es el archivo original. Al continuar se conservan los tiempos de subtítulos, notas y cortes, y se registra este archivo para futuras comprobaciones."],
  "원본으로 확인하고 연결":["Confirm original and connect","元ファイルと確認して接続","确认为原文件并连接","Confirmar original y conectar"],
  "원본 파일 확인 중… 큰 파일은 시간이 걸릴 수 있습니다.":["Verifying source file… Large files may take time.","元ファイルを確認中…大きなファイルは時間がかかる場合があります。","正在验证原始文件…大文件可能需要较长时间。","Verificando el original… Los archivos grandes pueden tardar."],
  "연결 취소":["Cancel connecting","接続をキャンセル","取消连接","Cancelar conexión"],
};
