export const mediaReconnectMessages: Record<string, [string, string, string, string]> = {
  '원본 위치 기록이 없습니다. 한 번 다시 연결하면 다음부터 자동 연결됩니다.': ['The original location is not saved yet. Relink it once to reconnect automatically next time.', '元ファイルの場所が未保存です。一度再接続すると次回から自動接続します。', '尚未记录原文件位置。重新连接一次后，下次将自动连接。', 'Aún no se guardó la ubicación del original. Vuelve a vincularlo una vez para conectarlo automáticamente en el futuro.'],
  '기억한 위치에서 원본을 찾지 못했습니다. 파일을 다시 연결하세요.': ['The original was not found at its saved location. Relink the file.', '保存した場所に元ファイルが見つかりません。再接続してください。', '在保存的位置找不到原文件，请重新连接。', 'No se encontró el original en la ubicación guardada. Vuelve a vincular el archivo.'],
  '기억한 위치의 파일 내용이 원본과 다릅니다. 원본 파일을 다시 연결하세요.': ['The file at the saved location differs from the original. Relink the original file.', '保存した場所のファイル内容が元と異なります。元ファイルを再接続してください。', '保存位置的文件内容与原文件不同，请重新连接原文件。', 'El contenido del archivo guardado es distinto del original. Vuelve a vincular el archivo original.'],
  '원본 자동 연결을 완료하지 못했습니다. 파일을 다시 연결하세요.': ['Automatic reconnection could not finish. Relink the file.', '元ファイルの自動接続を完了できませんでした。再接続してください。', '无法完成原文件自动连接，请重新连接。', 'No se pudo completar la conexión automática. Vuelve a vincular el archivo.'],
  '원본 자동 연결 결과를 확인할 수 없습니다. 파일을 다시 연결하세요.': ['The reconnected original could not be verified. Relink the file.', '自動接続した元ファイルを検証できません。再接続してください。', '无法验证自动连接的原文件，请重新连接。', 'No se pudo verificar el original reconectado. Vuelve a vincular el archivo.'],
  '원본 위치와 내용을 확인하고 자동 연결했습니다.': ['Original location and content verified. Reconnected automatically.', '元ファイルの場所と内容を確認し、自動接続しました。', '已验证原文件位置和内容，并自动连接。', 'Ubicación y contenido del original verificados. Conectado automáticamente.'],
  '원본 위치를 기억하지 못했습니다. 다음에 프로젝트를 열 때 다시 연결해야 합니다.': ['The original location could not be saved. You will need to relink it next time.', '元ファイルの場所を保存できませんでした。次回は再接続が必要です。', '无法保存原文件位置，下次打开项目时需要重新连接。', 'No se pudo guardar la ubicación del original. Tendrás que volver a vincularlo la próxima vez.'],
};
